@startuml
class Carro {
  +marca
  +modelo
  +ano
  +cor
  +velocidade

  +acelerar()
  +frear()
  +ligar()
  +desligar()
}

class Motor {
  +potencia
  +tipo

  +ligarMotor()
  +desligarMotor()
}

class Roda {
  +tamanho
  +tipo

  +girar()
  +frear()
  }

class Motorista {
  +nome
  +cnh
  +idade

  +dirigir()
  +estacionar()
}

class CarroEletrico {
  +autonomiaBateria: int
  +carregarBateria(): void
}

class CarroCombustao {
  +capacidadeTanque: int
  +abastecer(): void
}   

Carro "1" -- "1" Motor : possui
Carro "1" -- "N" Roda : possui

Carro "N" -- "N" Motorista

Motor <|-- CarroEletrico
Motor <|-- CarroCombustao

Carro "1" o-- "N" Roda : possui

Carro "1" *-- "1" Motor : contém












@enduml