@startuml
title "Caso de Uso - Usuário Reserva um Livro"

actor "Usuário autenticado" as Usuario
actor "Sistema de pagamento" as Pagamento

Usuario -> (Navegar na biblioteca)
Usuario -> (Selecionar um livro disponível)
Usuario --> (Reservar Livro)
Usuario --> (Verificar status de assinatura)

Pagamento <-- (Verificar status de assinatura) : Status da assinatura

(Reservar Livro) --> (Verificar limite de reservas)
(Verificar limite de reservas) --> Usuario : Limite excedido

(Verificar status de assinatura) --> (Reserva Imediata)
(Verificar limite de reservas) --> (Reserva Imediata)
(Reserva Imediata) --> (Atualizar Status do Livro)
(Atualizar Status do Livro) --> (Notificar Usuário)

(Selecionar um livro disponível) --> (Verificar Disponibilidade do Livro)
(Verificar Disponibilidade do Livro) --> Usuario : Livro indisponível

@enduml
