@startuml

' Casos de Uso
(First usecase)

(Another usecase) as (UC2)

usecase UC3

usecase (Last\n usecase) as UC4

' Atores
:First Actor:

:Another\n Actor: as Man2

actor Woman3
actor :Last actor: as Person1
"Main Admin" as Admin

' Relações
Man2 --> (Use the application)

Admin --> (Admin the application)
@enduml