# Generated by Django 5.1.2 on 2024-10-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('data_matricula', models.DateField()),
            ],
        ),
    ]
